### ISSUE TITLE
Remove body param from email log

### ISSUE THREAD

**Issue by gpalmisano** [dachcom-digital/pimcore-formbuilder#268]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Formbuilder v 3.3.6
Email CSV export of emails sent with standard mail template: Export ist empty, email is correct.
Email CSV export of emails sent with deactivated standard mail template: Export is correct, email is empty.

**Comment by solverat** [comment]
The real issue is the size of the email log field `params` which is a `text` type. Since we're also storing the `body` property (which is the rendered email body and can be huge sometimes) this will exceed given field space sometimes.
Removing the `body` property after the mail has sent should do the trick!
