### ISSUE TITLE
Where and how do you define the HoneyPot configuration?

### ISSUE THREAD

**Issue by SmashingQuasar** [dachcom-digital/pimcore-formbuilder#272]
Hey!

I am trying to set the Honeypot configuration as ReCaptcha cannot work on our customer's infrastructure and we need at least some protection.
I read the [03_SpamProtection](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/03_SpamProtection.md) file but I have to say it is really confusing.
What is the YAML structure for this file? Where is it stored? How do you load it? Is it automatically detected or should I load it manually? Does it apply to every form or is it necessary to load it for every brick declaration?

Thanks!

**Comment by solverat** [comment]
Well maybe it's confusing because you've mixed up your definition. The honeypot field is not related to the reCAPTCHA field. These are two different approaches to avoid spam.

The configuration is symfony standard and is very self-explaining if you have experience with it (which is a requirement if you're using pimcore anyway).

However, the Honeypot field is enabled by default and does not need any further configuration. The reCAPTCHA field on the other hand needs to be added on each form and configured like described in the README you've mentioned.
