### ISSUE TITLE
[FEATURE] Form Choice Field - multiple option missing min/max Validation

### ISSUE THREAD

**Issue by grizzlydotweb** [dachcom-digital/pimcore-formbuilder#298]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Multiple Choice Options 
the choice field is missing 4 form options if multiple is set:

| field                 | type      |
| ------------------- | -----------|
| max                 | int         |
| maxMessage   | string    |
| min                 | int        |
| minMessage | string    |

Or we implement it by adding the constraint:
https://symfony.com/doc/current/reference/constraints/Choice.html#max

if you are interested in adding this fields, i will be happy to make an PR.
Please give me some hints, if there are some constraints to do it and what i have to consider about.

**Comment by solverat** [comment]
@grizzlydotweb Choice Form Type does not provide any validation conditions, so it must be an additional constraint. 

In #380, I've added the `Choice` and the `Count` Constraint. In your case, the `Count` constraint would be the right one, since the `Choice` constraints is always bounded to given choices or a callback.
