### ISSUE TITLE
Birthday/DateTime/Date/Time Constraint: Clarify Usage

### ISSUE THREAD

**Issue by pascalmoser** [dachcom-digital/pimcore-formbuilder#379]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

the date constraint issues the following message when used for a date or birth field:
`This value should be of type string.`

**Comment by solverat** [comment]
Date [expects a string or an object that can be cast into a string](https://symfony.com/doc/current/reference/constraints/Date.html). 

In Symfony 4, it just returned without validating, now it's throwing a `Type` constraint exception.

It is not required, to add a Date* Constraint to a Date Form Field since it always has to be a valid \DateTime Instance.

However, in #380, I've added the `format` option to the Birthday, Date and DateTime Form Type.
